### ISSUE TITLE
Namespace

### ISSUE THREAD

**Issue by ben18785** [epiverse-trace/serofoi#62]
There are some functions which I wasn't sure should be external facing (i.e. available to users), which include:

*  `run_seromodel` calls `fit_seromodel` internally but the latter is also exported to the package namespace. I'd suggest removing that export since users wouldn't interface directly with `fit_seromodel`.
* `get_exposure_ages`
* `get_exposure_matrix`
* `get_prev_expanded`
* `prepare_bin_data`

**Comment by jpavlich** [comment]
I removed `@export` from
	- `fit_seromodel`
	- `get_exposure_matrix`
	- `get_prev_expanded`
	- `prepare_bin_data`
Following https://style.tidyverse.org/documentation.html#internal-functions I added `@noRd` to each function

I have these questions before commiting the code
1. Examples cannot be run for the above functions, since it shows a `function not found` error. One solution would be to use `:::` to refer to the functions, but that is not accepted by CRAN. The only alternative I know of is using `\dontrun{}`
	- Should I use `\dontrun{}` on those examples, so those comments are not lost, or should I remove those examples altogether? Are there any other alternatives to solve this issue?
2. The function `get_foi_central_estimates` uses `fit_seromodel`. Should I make `get_foi_central_estimates` internal or should I put back `@export` to `fit_seromodel`
